[versions]
android-gradle-plugin = "8.5.2"
androidx-junit = "1.1.5"
androidx-annotation = "1.3.0"
appcompat = "1.6.1"
constraintlayout = "2.1.4"
detekt = "1.22.0"
junit = "4.13.2"
kotlinPlugin = "1.9.10"
kotlinxSerializationJson = "1.6.0"
lifecycle-viewmodel = "2.6.1"
logging-interceptor = "4.9.1"
material = "1.9.0"
paging-common = "3.2.0"
retrofit = "2.9.0"
retrofit2KotlinxSerializationConverter = "1.0.0"
robolectric = "4.11.1"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
junit = { module = "junit:junit", version.ref = "junit" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-viewmodel" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle-viewmodel" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
material = { module = "com.google.android.material:material", version.ref = "material" }
paging-common = { module = "androidx.paging:paging-common", version.ref = "paging-common" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinPlugin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinPlugin" }

